version: "3.8"


services:
  judgehost-1:
    container_name: judgehost-1
    image: domjudge/judgehost:7.3.3
    hostname: judgedaemon-1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      DAEMON_ID: 1
      CONTAINER_TIMEZONE: Europe/Vienna
      JUDGEDAEMON_USERNAME: judgehost
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD:?}
      DOMSERVER_BASEURL: ${DOMSERVER_PROTOCOL:-https}://${DOMSERVER_URL:?}
  judgehost-2:
    container_name: judgehost-2
    image: domjudge/judgehost:7.3.3
    hostname: judgedaemon-2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      DAEMON_ID: 2
      CONTAINER_TIMEZONE: Europe/Vienna
      JUDGEDAEMON_USERNAME: judgehost
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD:?}
      DOMSERVER_BASEURL: ${DOMSERVER_PROTOCOL:-https}://${DOMSERVER_URL:?}
  judgehost-3:
    container_name: judgehost-3
    image: domjudge/judgehost:7.3.3
    hostname: judgedaemon-3
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      DAEMON_ID: 3
      CONTAINER_TIMEZONE: Europe/Vienna
      JUDGEDAEMON_USERNAME: judgehost
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD:?}
      DOMSERVER_BASEURL: ${DOMSERVER_PROTOCOL:-https}://${DOMSERVER_URL:?}
